dynamicResourcesPath: src/main/resources/dynamic/

spring:
  sql:
    init:
      mode: always
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5435/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false